### PR TITLE
Design pattern 2: strategy pattern and bug fixes <organisation, bug, feature>

### PR DESCRIPTION
**Pull request by MatthijsRijlaarsdam**

### CODE REVIEW

**Comment by Premmie** [comment]
Good thing to change Assets to private.  <organisation

**Comment by DaanVermunt** [comment]
Great job implementing the strategy pattern <organisation>

**Comment by DaanVermunt** [comment]
Making all assets private is kind of unnecessary in my opinion, but not really a big issue, maybe javadoccing the getters is a good idea <layout>

**Comment by MatthijsRijlaarsdam** [comment]
Yeah, aaron told us that was an issue. I'll add comments <documentation

**Comment by DaanVermunt** [comment]
Oke clear and goog job going to merge

**Pull request merged**
