### PR TITLE
restrucuterd classes RDD <organisation>

### PR DESCRIPTION
**Pull request by MatthijsRijlaarsdam**

### CODE REVIEW

**Comment by arjovanramshorst** [comment]
Alright, everything should be working now, and should be up to date with master. Please check, and then I'll merge it.

**Comment by wouterz** [comment]
A lot of testing removed from playerObjectTesting leaving more untested, did all of this need to be removed? <testing, review

**Comment by arjovanramshorst** [comment]
Not true, all those tests are in another branch.

**Comment by arjovanramshorst** [comment]
Should be fixed now.

**Comment by wouterz** [comment]
Good to go
<testing, organisation, naming

**Pull request merged**
